### ISSUE TITLE
How to convert the 128 char seed into a normal nano 64 char seed?

### ISSUE THREAD

**Issue by Joohansson** [numsu/nanocurrency-web-js#3]
There is no mention in the nano docs how to do that. https://docs.nano.org/integration-guides/key-management/#test-vectors
I need to convert a 64 char seed into mnemonic and vice versa but this lib only take 128 char seed.

**Comment by numsu** [comment]
The way that Natrium etc. wallets are currently doing the mnemonic phrases is not an official way of doing it. These two ways are incompatible with each other. I'm planning on adding support for the another kind of mnemonic and seed to this library at a later time.

I haven't looked into it yet, but I suspect that they're just converting the seed to binary and making the mnemonic from that input.

**Comment by Joohansson** [comment]
I actually managed to solve it. I'm using a combination of this library, [nanocurrency-js](https://github.com/marvinroger/nanocurrency-js/tree/master/packages/nanocurrency) and [bip39](https://www.npmjs.com/package/bip39). Specifically
```
    let seed = bip39.mnemonicToEntropy(mnemonic).toUpperCase()
    let nanowallet = wallet.generate(seed)
    var privKey
    if (this.state.selectedDerivationMethod === '0') {
      privKey = nano.deriveSecretKey(seed, index)
    }
    else {
      let accounts = wallet.accounts(nanowallet.seed, index, index)
      privKey = accounts[0].privateKey
    }
    let pubKey = nano.derivePublicKey(privKey)
    let address = nano.deriveAddress(pubKey, {useNanoPrefix: true})
```

You can see it in action here providing both derivation methods. I will present this toolbox in a week or so. Please don't share it yet.
https://tools.nanos.cc/?tool=seed
